use_frameworks!

platform :ios, '10.0'

target 'PLPaymentGatewayPod_Example' do
  pod 'PLPaymentGatewayPod', :path => '../'

  target 'PLPaymentGatewayPod_Tests' do
    inherit! :search_paths

    
  end
end
